### ISSUE TITLE
Badge Number Display Position

### ISSUE THREAD

**Issue by ultrasilicon** [ultrasilicon/Hive#16]
* There's a random shift of the position of number label

**Comment by Linghua-Mao** [comment]
if I use the software in Vmware of Linux and in Windows,but the the version of windows is 0.0.4,and the one in Linux is 0.0.7 alpha, and I find the windows can find the Vmware one but the Vmware couldn't find the windows one, why? is the reason of code?

**Comment by ultrasilicon** [comment]
Hi Linghua-Mao ,
Theoretically, you can find other online users once you are in the same domain. I am not sure how Vmware deals with network connection for the system running on it, especially when you have a proxy configured. Here are things that are surely working and surely not working:
- Not working: sending messages
  - In 0.0.4, the message data is in the format of C++ stream; but in 0.0.7, the message data is an JSON Object.
- Working: finding other users
  - In both versions, the "greetings", which is sent to be found by other users, are sent and listened in the same way. 

I hope this will help you, but I'm sorry that I have never tested Hive in virtual machine, so I don't know exactly where the problem is. 

Tim Z.
