### ISSUE TITLE
Hive for Linux

### ISSUE THREAD

**Issue by ultrasilicon** [ultrasilicon/Hive#6]
1. Font size too big
2. IP status indicator too large, try more UTF-8 characters.

**Comment by ultrasilicon** [comment]
1. Solved

**Comment by marksugar** [comment]
这怎么用啊。。。。我都git下来，发现不知道怎么用

**Comment by ultrasilicon** [comment]
用Qt编译一下，debian的话sudo apt-get install qt5装一下然后编译就可以啦
